apiVersion: v1
kind: Service
metadata:
  name: example-webhook
  namespace: default
spec:
  selector:
    app: example-webhook
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-webhook
  namespace: default
  labels:
    app: example-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-webhook
  template:
    metadata:
      labels:
        app: example-webhook
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: example-webhook
      containers:
      - name: server
        image: abdulrhmanaly/webhook-ksniff:v3.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: tls
          hostIP: 10.244.1.2
        - containerPort: 80
          name: metrics
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /etc/webhook/certs/
          readOnly: true
        - name: my-volume
          mountPath: /tmp/test/
        - name: data-volume
          mountPath: /mnt/data/input  # Mount to /mnt/data/input inside container
          subPath: input  # Ensure data is written to the 'input' subdirectory on host
        - name: data-volume
          mountPath: /mnt/data/output  # Mount to /mnt/data/output inside container
          subPath: output  
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cicflowmeter-pvc
      - name: webhook-tls-certs
        secret:
          secretName: example-webhook-tls
      - name: my-volume
        configMap:
          name: my-config
